// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmetSFwEKsCsPypJ2GtrK-VUskdaluZk',
    appId: '1:343489139900:web:ec17378d61b33693c6ecb9',
    messagingSenderId: '343489139900',
    projectId: 'studybuddy-32219',
    authDomain: 'studybuddy-32219.firebaseapp.com',
    storageBucket: 'studybuddy-32219.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeX0GCu1H6Ca68jS0rUCzeojhP_ilOIo',
    appId: '1:343489139900:android:d92fa9aeead4f567c6ecb9',
    messagingSenderId: '343489139900',
    projectId: 'studybuddy-32219',
    storageBucket: 'studybuddy-32219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0xCmFrPOYR48KtZcAIDgn2Jf6jZj-Vc',
    appId: '1:343489139900:ios:ecc7e2bb5cabe1d8c6ecb9',
    messagingSenderId: '343489139900',
    projectId: 'studybuddy-32219',
    storageBucket: 'studybuddy-32219.firebasestorage.app',
    iosBundleId: 'com.example.senior2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0xCmFrPOYR48KtZcAIDgn2Jf6jZj-Vc',
    appId: '1:343489139900:ios:ecc7e2bb5cabe1d8c6ecb9',
    messagingSenderId: '343489139900',
    projectId: 'studybuddy-32219',
    storageBucket: 'studybuddy-32219.firebasestorage.app',
    iosBundleId: 'com.example.senior2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmetSFwEKsCsPypJ2GtrK-VUskdaluZk',
    appId: '1:343489139900:web:62fd920fd61055b5c6ecb9',
    messagingSenderId: '343489139900',
    projectId: 'studybuddy-32219',
    authDomain: 'studybuddy-32219.firebaseapp.com',
    storageBucket: 'studybuddy-32219.firebasestorage.app',
  );
}
